Fix Clang warnings
jrmuizel/qcms pull request #4
Opened 2015-06-30 08:54 UTC by mgiuca

Second try, this time based against the v4 branch which appears to be the focus of development. To verify, edit `Makefile` as follows:

Add line `CC=clang`. Add `-lm` to `LDFLAGS`. Run `make -B`.

This came up trying to build Chromium on Windows with Clang (but actually it turns out all the Chromium issues are fixed now, so this is not required for Chromium).

Cheers

Matt (mgiuca@chromium.org)

2015-06-30 13:49 UTC, jrmuizel commented
The version on github has come out of sync with the upstream version in mozilla. I'll update it today and you can rebase your changes on top of that.

2015-07-01 00:46 UTC, mgiuca commented
So is the Mozilla one the canonical one? Should I just sent patches to the [mozilla-central](https://hg.mozilla.org/mozilla-central/file/tip/gfx/qcms) repo in future?

2015-07-01 04:24 UTC, jrmuizel commented
That would be easier for me.

2018-04-27 20:04 UTC, boonsom approved these changes

2024-02-14 01:56 UTC, Lupillo07 requested changes
Quitar parrofo 37

2024-02-14 01:58 UTC, Lupillo07 requested changes
37 (qcms_profile *outputprofile)

2024-02-14 01:58 UTC, Lupillo07 requested changes
37 (qcms_profile *outputprofile)

2024-02-14 01:58 UTC, Lupillo07 requested changes
37 (qcms_profile *outputprofile)

2024-02-14 15:08 UTC, closed without merging